---
apiVersion: v1
kind: Service
metadata:
  name: nlb-test
  namespace: default
  labels:
    app: nlb-test
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: nlb-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlb-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nlb-test
    spec:
      containers:
      - name: nlb-test
        image: 860498507463.dkr.ecr.us-west-2.amazonaws.com/nlb-test:ed75af9-dirty
        ports:
        - containerPort: 8000
        env:
        - name: URL
          value: "http://ae35bcc3f30d911e88672066e78bb0cd-49118c41d965be0f.elb.us-west-2.amazonaws.com"
        
